### ISSUE TITLE
More of a question than an issue

### ISSUE THREAD

**Issue by osteichthyes** [nning/linux-grsec#7]
I've been building my own grsecurity kernel for about a year that I forked from you.

Since ~4.8.10 or so, I've had regular boot issues. In particular, issues with systemd-logind repeatedly mounting and unmounting a tmpfs, then failing. After doing so thousands of times, it eventually failed and the computer hangs. I tried installing your precompiled package from the repos, and it booted fine. I then basically started moving my config closer to yours in groups of ~10-20 flags at a time. In the end, it seemed more random than anything. Some would boot, some wouldn't. My last one from the 22 Feb patchset booted, with all of my config switches identical to yours save a few in the grsecurity patch set. Now, in the 5 March patch, I once again cannot boot. 

I've already reached out on the grsecurity forums, but since many users are on gentoo and other distros, I thought I'd see if you've had any similar issues and/or any advice. 

Thanks so much for your time!
Scott

**Comment by nning** [comment]
I did not encounter such issues, yet. Could you attach a config for the most current patchset version that has this problem on your machine? You are using x86_64, I presume? Do you have any unusual hardware configuration?

**Comment by osteichthyes** [comment]
The most recent build I attempted worked on 12 March, but then failed on the 15 March patchset. At the moment, my config is identical to yours except I turned off 
GRKERNSEC_KMEM
GRKERNSEC_ROFS

And turned on
GRKERNSEC_SYSFS_RESTRICT

Other than that, my config is identical to yours (it's also a few versions newer -- it has a few new features).

I'll push mine shortly.

**Comment by nning** [comment]
That sounds more like an issue for the grsecurity forums. However, I will try to build and boot with your options in the next few days.

**Comment by nning** [comment]
I could boot with the configuration you described in a VM without any apparent issues.

**Comment by nning** [comment]
Sorry, I could not help; is closing the issue fine for you?

**Comment by osteichthyes** [comment]
Yep, thanks. I'm lost, it's got to be an issue in my build environment, but I cannot seem to figure out what is causing it. Even when I turn off the grsecurity patchset, it fails. I was using the hardening-wrapper, but I removed that and tried again, yielding yet another unbootable kernel.

Thanks again
